#! /bin/bash
# Echo help for fom

echo -e "\nHelp"
echo -e "----\n"
echo -e "This help provides a list of commands for \e[34mfom\e[0m package (folder management)"
echo -e " "
echo -e "\e[93mfom-folders\e[0m - lists folders in the current directory"
echo -e "\e[93mfom-tasks\e[0m   - lists tasks in the current directory"
echo -e "\e[93mfom-help\e[0m    - prints this help\n\n"

