#! /bin/bash
# Připravuje text ke zpracování

rm files
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

ln -s $DIR/../files/ files


xelatex $1
biber $1
xelatex $1
xelatex $1
rm $1.aux $1.bbl $1.bcf $1.blg $1.log $1.lot $1.out $1.run.xml $1.toc texput.log

